# Generated by Django 2.1.7 on 2019-03-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_langauage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Langauage',
            new_name='Language',
        ),
    ]
