# Generated by Django 2.1.7 on 2019-03-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190310_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='langauge',
            field=models.ForeignKey(help_text='Select a langauge for the book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
    ]
